version: 2.1

jobs:
  process_datasets:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Process Datasets
          command: python process_datasets.py

workflows:
  scheduled_pipeline:
    triggers:
      - schedule:
          cron: "H/10 * * * *"  # Corrected cron syntax
          filters:
            branches:
              only:
                - main
    jobs:
      - process_datasets