name: Process Datasets

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  process_datasets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set HF Credentials
        run: |
            echo "HF_USERNAME=${{ secrets.HF_USERNAME }}" >> $GITHUB_ENV
            echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Process Datasets
        run: python process_datasets.py